### ISSUE TITLE
Create disallow list as the sitemaps list

### ISSUE THREAD

**Issue by leccyril** [pandzel/RobotsTxt#2]
It should be great to have like getSitemaps() list, the disallow list for a specifiq agent, for example getDisallowList("*") 👍 

/test/*
/test2/test3.html

....
because for example we have to record the disallow list to reuse later 
do you think it is possible to do ? 

thank you !

**Comment by pandzel** [comment]
Yes, it is. In fact I have already made that change and push to the code repository. 
It is not available in Maven Central yet, so you might be tempted to build it yourself.

**Comment by leccyril** [comment]
u tell me to upload it manually on the mvn repository or to download it and use it as library ? because i could not do the last, i have to use i as a dependency in playframework application

**Comment by pandzel** [comment]
I have uploaded it to Maven Central already and I can tell that the new version is available already, so you may give a try and just use it (new version is 1.1.0).

Back to your question: in case like that the only thing you need to do is to clone project to your local folder and build it using 'mvn clean install'. That will create an artifact in your local maven repository, ready to bind to your own project.

**Comment by leccyril** [comment]
Thank you , yes i know but In production i could not install maven and build directly from a local reprository  it is a cluster server and more complex to achieve it !!!
