### ISSUE TITLE
Problem with decoding URL

### ISSUE THREAD

**Issue by Mahmoud-Khaled-Nasr** [pandzel/RobotsTxt#4]
I am using this library in my Crawler it throws the following exception 
> Exception in thread "Thread-0" java.lang.IllegalArgumentException: URLDecoder: Incomplete trailing escape (%) pattern
	at java.net.URLDecoder.decode(URLDecoder.java:187)
	at com.panforge.robotstxt.URLDecoder.decode(URLDecoder.java:37)
	at com.panforge.robotstxt.RobotsTxtReader.parseEntry(RobotsTxtReader.java:177)
	at com.panforge.robotstxt.RobotsTxtReader.readEntry(RobotsTxtReader.java:139)
	at com.panforge.robotstxt.RobotsTxtReader.readRobotsTxt(RobotsTxtReader.java:64)
	at com.panforge.robotstxt.RobotsTxt.read(RobotsTxt.java:72)
	at crawler.RobotMonitor.fetchRobot(RobotMonitor.java:81)
	at crawler.RobotMonitor.getRobot(RobotMonitor.java:59)
	at crawler.RobotMonitor.isAllowed(RobotMonitor.java:32)
	at crawler.Leg.run(Leg.java:44)
	at java.lang.Thread.run(Thread.java:745)

for accessing the following URL: https://keep.google.com/robots.txt
I traced the bug to function decode in by the **RobotsTxtReader** class and I think I can fix it or there is a problem with my implementation.
```
private RobotsTxt fetchRobot(String url) {
        InputStream robotsTxtStream = null;
        RobotsTxt robotsTxt = null;
        try {
            robotsTxtStream = new URL(url).openStream();
        } catch (IOException e) {
            e.printStackTrace();
        }
        try {
            robotsTxt = RobotsTxt.read(robotsTxtStream);
        } catch (IOException e) {
            e.printStackTrace();
        }
        return robotsTxt;
    } 
```

**Comment by pandzel** [comment]
It has to do something with "keep.google.com", I presume.

Line: robotsTxtStream = new URL(url).openStream(); gives a stream to the content which is not a robots.txt content but rather an HTML page requesting you to sign in. Try it yourself:
<code><pre>
    URL url = new URL("https://keep.google.com/robots.txt");
    try (InputStream inputStream = url.openStream(); BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream, "UTF-8")); ) {
      String line = null;
      while ((line = reader.readLine()) != null) {
        System.out.println(line);
      }
    }
</pre></code>

My guess is that keep.google.com requires some particular request header or cookie.

**Comment by Mahmoud-Khaled-Nasr** [comment]
Hi,
Thanks for the fast response.

I tested your theory and I found out it redirects to another URL with the robots.txt
https://keep.google.com/u/0/robots.txt
but still I think a simple adjustment can fix this exception especially it is thrown by URL class which isn’t nice at all.

Regards.

Sent from Mail for Windows 10

**Comment by pandzel** [comment]
Related too #7. Recommended to use third party library as HTTP client (for example Apache HTTP client).
